/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

// Librerias de conexion
import java.sql.Connection;//conexion a BD
import java.sql.DriverManager;//Driver de conexion
import java.sql.ResultSet;//Resultado final de datos
import java.sql.ResultSetMetaData;//Resultado de metadatos
import java.sql.SQLException;//Tratamiento de Errores de BD SQL
import java.sql.Statement;//Generador de sentencias sql DDL,MDL,DCL
import java.text.SimpleDateFormat;//Formatear datos
import java.util.Date;//Fecha de sistema
import java.util.Set;
import javax.swing.ImageIcon;//Tratamiento de imagenes
import javax.swing.JOptionPane;//ventanas emergentes
import javax.swing.table.DefaultTableModel; //tabla de datos
import pojos.Cliente;
import sun.net.smtp.SmtpClient;

import pojos.Temporal;


//Librerias reporte e imprimir
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author leonv
 */
public class CRUDContacto extends javax.swing.JFrame {
    
    Cliente objCliente = new Cliente();//generacion del objeto libro
    
    //clases de conexion y sus objetos
    public Connection cn;
    public Statement stmt;
    public ResultSet rs;

    /** Creates new form CRUDContacto */
    public CRUDContacto() {
        initComponents();
        
        mostrarClientes();
        
        Temporal tempo = new Temporal();
        String str = convertirMayusculas(tempo.getTipoUsuario());
        
        lblTipoUsuario.setText(str);
        lblSaludo.setText("Bienvenido "+tempo.getUsuario());
        
        ocultarPanel(tempo);
        
    }
    
    public void ocultarPanel(Temporal tempo){
    
         if(tempo.getTipoUsuario().equals("visitante")){
             
             pnlContenedor.setVisible(false);
            
        }
    
    }
    
    public String convertirMayusculas(String palabra){
        
        String firstLtr = palabra.substring(0, 1);
        String restLtrs = palabra.substring(1, palabra.length());
        firstLtr = firstLtr.toUpperCase();
        palabra = firstLtr+restLtrs;
        
        return palabra;
    }
    
    
     public void conectarBase(){
    
        try{//inicia try
        
            Class.forName("com.mysql.jdbc.Driver");
            cn = DriverManager.getConnection("jdbc:mysql://localhost/leo_bd","root","");
           // JOptionPane.showMessageDialog(null, "Conexion a BD OK\n\nCASTRO");
            stmt = cn.createStatement();
        }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, "Error de base de datos 1: \n"+ ex);
        }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error de base de datos 2:"+e);
        }
    }//termina metodo conectar

    public void mostrarClientes(){
        
        try {
            conectarBase();//llamada a la conexion
            //Declaracion de un objeto de almacenamiento logico de datos "Modelo de datos"
            DefaultTableModel modeloDatos = new DefaultTableModel();
            jtConsulta.setModel(modeloDatos);

            rs=stmt.executeQuery("SELECT * FROM tcliente");
            //imprimir y contar columnas
            ResultSetMetaData rsmd = rs.getMetaData();
            int cantidadColumnas = rsmd.getColumnCount();
            modeloDatos.addColumn("Id Cliente");
            modeloDatos.addColumn("Nombre");
            modeloDatos.addColumn("Dirección");
            modeloDatos.addColumn("País");
            modeloDatos.addColumn("Correo");
            modeloDatos.addColumn("Teléfono");
            
            modeloDatos.addColumn("CP");
            modeloDatos.addColumn("Tipo cliente");
            modeloDatos.addColumn("Puesto");
            modeloDatos.addColumn("Empresa");
            modeloDatos.addColumn("Giro");
            modeloDatos.addColumn("Observaciones");
 
            //imprimir filas o registros
            while(rs.next()){//inicia while
                Object fila [] = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    fila[i]=rs.getObject(i+1);
                }
                modeloDatos.addRow(fila);
            }//termina while

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, "Error 2 de BD Consulta" +e);
        }
    }
     
     
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenedor = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblPais = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtPais = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        txtTipoCliente = new javax.swing.JTextField();
        txtPuesto = new javax.swing.JTextField();
        txtCP = new javax.swing.JTextField();
        txtNombreEmpresa = new javax.swing.JTextField();
        txtGiro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        lblTelefono2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblId1 = new javax.swing.JLabel();
        txt_E_Id = new javax.swing.JTextField();
        lblNombre1 = new javax.swing.JLabel();
        txt_E_Nombre = new javax.swing.JTextField();
        lblDireccion1 = new javax.swing.JLabel();
        txt_E_Direccion = new javax.swing.JTextField();
        lblPais1 = new javax.swing.JLabel();
        txt_E_Pais = new javax.swing.JTextField();
        lblCorreo1 = new javax.swing.JLabel();
        txt_E_Correo = new javax.swing.JTextField();
        lblTelefono1 = new javax.swing.JLabel();
        txt_E_Telefono = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_E_Observaciones = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        txt_E_TipoCliente = new javax.swing.JTextField();
        txt_E_Puesto = new javax.swing.JTextField();
        txt_E_NombreEmpresa = new javax.swing.JTextField();
        txt_E_Giro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_E_CP = new javax.swing.JTextField();
        lblTelefono3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtId_B = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtConsulta = new javax.swing.JTable();
        lblSaludo = new javax.swing.JLabel();
        lblTipoUsuario = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnDescargarPDF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar Contacto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        lblId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblId.setText("Id:");

        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNombre.setText("Nombre:");

        lblDireccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDireccion.setText("Dirección:");

        lblPais.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPais.setText("País:");

        lblCorreo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCorreo.setText("Correo:");

        lblTelefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTelefono.setText("Teléfono:");

        txtId.setToolTipText("");
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Tipo Cliente:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Puesto:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Nombre Empresa:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Giro:");

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane2.setViewportView(txtObservaciones);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Observaciones:");

        lblTelefono2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTelefono2.setText("C.P:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegistrar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNombre)
                            .addComponent(lblId)
                            .addComponent(lblDireccion)
                            .addComponent(lblPais)
                            .addComponent(lblCorreo)
                            .addComponent(lblTelefono)
                            .addComponent(lblTelefono2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCP)
                            .addComponent(txtId)
                            .addComponent(txtNombre)
                            .addComponent(txtDireccion)
                            .addComponent(txtPais)
                            .addComponent(txtCorreo)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(95, 95, 95)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTipoCliente)
                                .addComponent(txtPuesto)
                                .addComponent(txtNombreEmpresa)
                                .addComponent(txtGiro, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre)
                    .addComponent(txtPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPais)
                    .addComponent(txtGiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblCorreo)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefono))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelefono2)
                            .addComponent(txtCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegistrar)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pnlContenedor.addTab("Registrar Contacto", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editar Contacto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        lblId1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblId1.setText("Id:");

        txt_E_Id.setToolTipText("");
        txt_E_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_E_IdActionPerformed(evt);
            }
        });

        lblNombre1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNombre1.setText("Nombre:");

        lblDireccion1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDireccion1.setText("Dirección:");

        lblPais1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPais1.setText("País:");

        lblCorreo1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCorreo1.setText("Correo:");

        lblTelefono1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTelefono1.setText("Teléfono:");

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        txt_E_Observaciones.setColumns(20);
        txt_E_Observaciones.setRows(5);
        jScrollPane3.setViewportView(txt_E_Observaciones);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Observaciones:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Tipo Cliente:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Puesto:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Nombre Empresa:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Giro:");

        txt_E_CP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_E_CPActionPerformed(evt);
            }
        });

        lblTelefono3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTelefono3.setText("C.P:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEditar)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDireccion1)
                            .addComponent(lblTelefono1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCorreo1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPais1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNombre1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblId1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTelefono3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_E_Id)
                                .addComponent(txt_E_Nombre)
                                .addComponent(txt_E_Direccion)
                                .addComponent(txt_E_Pais)
                                .addComponent(txt_E_Correo)
                                .addComponent(txt_E_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_E_CP, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_E_TipoCliente)
                                .addComponent(txt_E_Puesto)
                                .addComponent(txt_E_NombreEmpresa)
                                .addComponent(txt_E_Giro, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblId1)
                            .addComponent(txt_E_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_E_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre1))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDireccion1)
                            .addComponent(txt_E_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_E_Pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPais1))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCorreo1)
                            .addComponent(txt_E_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_E_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_E_CP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefono3)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_E_TipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_E_Puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_E_NombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_E_Giro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGap(13, 13, 13)
                .addComponent(btnEditar)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pnlContenedor.addTab("Editar Contacto", jPanel2);

        jPanel3.setBackground(new java.awt.Color(189, 219, 240));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Borrar Contacto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Captura ID del contacto a eliminar");

        btnEliminar.setText("Eliminar Contacto");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtId_B)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(287, 287, 287))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel12)
                .addGap(33, 33, 33)
                .addComponent(txtId_B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        pnlContenedor.addTab("Borrar Contacto", jPanel3);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema de Registro de Contactos");

        jtConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Cliente", "Nombre", "Dirección", "País", "Correo", "Teléfono", "CP", "Tipo cliente", "Puesto", "Empresa", "Giro", "Observaciones"
            }
        ));
        jScrollPane1.setViewportView(jtConsulta);

        lblSaludo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSaludo.setForeground(new java.awt.Color(0, 7, 255));
        lblSaludo.setText("usuario");

        lblTipoUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTipoUsuario.setText("Tipo de usuario");

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnDescargarPDF.setText("Descargar PDF");
        btnDescargarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescargarPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1521, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSaludo)
                            .addComponent(lblTipoUsuario)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(290, 290, 290))
                            .addComponent(btnDescargarPDF))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTipoUsuario)
                .addGap(18, 18, 18)
                .addComponent(lblSaludo)
                .addGap(27, 27, 27)
                .addComponent(pnlContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnDescargarPDF)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

          // llama a el metodo conectar
        conectarBase();
        
        //Almacenar los valores del formulario objeto
        objCliente.setId(Integer.parseInt(txtId.getText()));
        objCliente.setNombre(txtNombre.getText());
        objCliente.setDireccion(txtDireccion.getText());
        objCliente.setPais(txtPais.getText());
        objCliente.setCorreo(txtCorreo.getText());
        objCliente.setTelefono(Integer.parseInt(txtId.getText()));
        
        objCliente.setCodigoPostal(Integer.parseInt(txtCP.getText()));
        objCliente.setTipoCliente(txtTipoCliente.getText());
        objCliente.setPuesto(txtPuesto.getText());
        objCliente.setNombreEmpresa(txtNombreEmpresa.getText());
        objCliente.setGiro(txtGiro.getText());
        objCliente.setObservaciones(txtObservaciones.getText());
        
        
        //variable objeto para registrar alumno
        String altaCliente="INSERT INTO tcliente(`id`,`nombre`,`direccion`,`pais`, `correo`, `telefono`, `codigo_postal`, `tipo_cliente`, `puesto`, `nombre_empresa`, `giro`, `observaciones`)"
                + "VALUES('"+objCliente.getId()+"','"
                +objCliente.getNombre()+"','"
                +objCliente.getDireccion()+"','"
                +objCliente.getPais()+"','"
                +objCliente.getCorreo()+"','"
                +objCliente.getTelefono()+"','"
                +objCliente.getCodigoPostal()+"','"
                +objCliente.getTipoCliente()+"','"
                +objCliente.getPuesto()+"','"
                +objCliente.getNombreEmpresa()+"','"
                +objCliente.getGiro()+"','"
                +objCliente.getObservaciones()+"')";
        
        //estructura de control de tratamiento de errores en ejecucion
        try{
            stmt.executeUpdate(altaCliente);
            JOptionPane.showMessageDialog(null, "Se registro cliente de forma exitosa "+objCliente.getNombre());
            mostrarClientes();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error 1 de BD al generar alta Libro\n\nVerifica\n\n"+ e);
        }


    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txt_E_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_E_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_E_IdActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed


        // llama a el metodo conectar
        conectarBase();
        
        //Almacenar los valores del formulario objeto
        objCliente.setId(Integer.parseInt(txt_E_Id.getText()));
        objCliente.setNombre(txt_E_Nombre.getText());
        objCliente.setDireccion(txt_E_Direccion.getText());
        objCliente.setPais(txt_E_Pais.getText());
        objCliente.setCorreo(txt_E_Correo.getText());
        objCliente.setTelefono(Integer.parseInt(txt_E_Id.getText()));
        
        
        objCliente.setCodigoPostal(Integer.parseInt(txt_E_CP.getText()));
        objCliente.setTipoCliente(txt_E_TipoCliente.getText());
        objCliente.setPuesto(txt_E_Puesto.getText());
        objCliente.setNombreEmpresa(txt_E_NombreEmpresa.getText());
        objCliente.setGiro(txt_E_Giro.getText());
        objCliente.setObservaciones(txt_E_Observaciones.getText());
       
       
        
        String actualizaCliente="UPDATE tcliente SET nombre='"
                +objCliente.getNombre()
                +"', direccion='"+objCliente.getDireccion()
                +"', pais='"+objCliente.getPais()
                +"', correo='"+objCliente.getCorreo()
                +"', telefono='"+objCliente.getTelefono()
                +"', codigo_postal='"+objCliente.getCodigoPostal()
                +"', tipo_cliente='"+objCliente.getTipoCliente()
                +"', puesto='"+objCliente.getPuesto()
                +"', nombre_empresa='"+objCliente.getNombreEmpresa()
                +"', giro='"+objCliente.getGiro()
                +"', observaciones='"+objCliente.getObservaciones()
                +"' WHERE id = '"+objCliente.getId()+"'";

        //estructura de control de tratamiento de errores en ejecucion
        try{
            stmt.executeUpdate(actualizaCliente);
            JOptionPane.showMessageDialog(null, "Cliente actualizado de forma exitosa "+objCliente.getId());
            mostrarClientes();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al actualizar el cliente de la BD\n\nVerifica\n\n"+ e);
        }
        
        
        

    }//GEN-LAST:event_btnEditarActionPerformed

    private void txt_E_CPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_E_CPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_E_CPActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        int confirmaBaja;

        try {
            conectarBase();
            int contactoBaja = Integer.parseInt(txtId_B.getText());

            confirmaBaja = stmt.executeUpdate("DELETE FROM tcliente WHERE id ='"+contactoBaja+"' " );

            if (confirmaBaja==1) {
                JOptionPane.showMessageDialog(null, "Se dio de baja el contacto de la base de datos " +contactoBaja+"\nVerifica Consulta");
                mostrarClientes();

            } else {
                JOptionPane.showMessageDialog(null, "Error! No existe el Id del contacto en la base de datos "+contactoBaja+"\nVerifica Consulta");
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al procesar baja de la Bases de datos\n\n"+ex);
        }
        
        
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Login ventanaLogin = new Login();
        Temporal tempo = new Temporal();
        
        JOptionPane.showMessageDialog(null, "Regresa pronto " +tempo.getUsuario());
        ventanaLogin.setVisible(true);
        this.hide();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnDescargarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescargarPDFActionPerformed
        
        
                conectarBase();
	        try {
	            String rutaReporte = "src/reportes/rptContactos.jasper";
	            JasperPrint rptContactosPDF = JasperFillManager.fillReport(rutaReporte,null,cn);
	            JasperViewer ventanaVisor = new JasperViewer(rptContactosPDF,false);
	            ventanaVisor.setTitle("Reporte de Equipo Sistema Cartera de Clientes");
	            ventanaVisor.setVisible(true);
	        } catch (Exception e) {
	            JOptionPane.showMessageDialog(null,"Error de BD en informe Verifica\n\n"+e);
	        }
    }//GEN-LAST:event_btnDescargarPDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUDContacto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDescargarPDF;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jtConsulta;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCorreo1;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDireccion1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblId1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblPais;
    private javax.swing.JLabel lblPais1;
    private javax.swing.JLabel lblSaludo;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTelefono1;
    private javax.swing.JLabel lblTelefono2;
    private javax.swing.JLabel lblTelefono3;
    private javax.swing.JLabel lblTipoUsuario;
    private javax.swing.JTabbedPane pnlContenedor;
    private javax.swing.JTextField txtCP;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtGiro;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtId_B;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreEmpresa;
    private javax.swing.JTextArea txtObservaciones;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtPuesto;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTipoCliente;
    private javax.swing.JTextField txt_E_CP;
    private javax.swing.JTextField txt_E_Correo;
    private javax.swing.JTextField txt_E_Direccion;
    private javax.swing.JTextField txt_E_Giro;
    private javax.swing.JTextField txt_E_Id;
    private javax.swing.JTextField txt_E_Nombre;
    private javax.swing.JTextField txt_E_NombreEmpresa;
    private javax.swing.JTextArea txt_E_Observaciones;
    private javax.swing.JTextField txt_E_Pais;
    private javax.swing.JTextField txt_E_Puesto;
    private javax.swing.JTextField txt_E_Telefono;
    private javax.swing.JTextField txt_E_TipoCliente;
    // End of variables declaration//GEN-END:variables

}
